use super::super::*;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use base64::{Engine as _, engine::general_purpose::STANDARD};
use tower::ServiceExt;

#[tokio::test]
async fn bundle_metadata_is_returned_and_reports_stale_source_files() {
    let temp = make_temp_dir();
    let worker_bin = bin("worker-runtime-host-worker");
    let wrangler_bin = temp.path().join("bin/wrangler");
    make_executable(&wrangler_bin, &fake_wrangler_script());

    let source_root = temp.path().join("project");
    std::fs::create_dir_all(source_root.join("src")).expect("source dir");
    std::fs::create_dir_all(source_root.join("build")).expect("build dir");
    let source_file = source_root.join("src/lib.rs");
    let artifact_file = source_root.join("build/index.js");
    std::fs::write(&source_file, "pub fn version() -> u8 { 1 }\n").expect("source file");
    std::fs::write(&artifact_file, "export default {};\n").expect("artifact file");

    let config = test_config(
        &temp,
        &worker_bin.display().to_string(),
        &wrangler_bin.display().to_string(),
        1,
    );
    let router = worker_runtime_host_gen::docs::app(config, test_plan());

    let created = request(
        router.clone(),
        axum::http::Method::POST,
        "/leases",
        serde_json::json!({
            "name": "metadata-test",
            "health_path": "/health"
        }),
    )
    .await;
    let lease_id = created["id"].as_str().expect("id");

    let bundled = request(
        router.clone(),
        axum::http::Method::POST,
        &format!("/leases/{lease_id}/bundle"),
        serde_json::json!({
            "runtime_files": [
                {
                    "path": "build/index.js",
                    "content_b64": STANDARD.encode("export default {};\n")
                }
            ],
            "metadata": {
                "source_root": source_root.display().to_string(),
                "build_command": "worker-build --release",
                "artifact_paths": ["build/index.js"],
                "source_paths": ["src/lib.rs"],
                "source_fingerprint": "git:abc123",
                "bundle_description": "project/build/index.js generated by worker-build"
            }
        }),
    )
    .await;

    assert_eq!(bundled["status"]["state"], "bundled");
    assert_eq!(
        bundled["bundle_metadata"]["bundle_description"],
        "project/build/index.js generated by worker-build"
    );
    assert!(bundled["bundle_uploaded_at"].as_str().is_some());
    assert!(bundled["bundle_diagnostics"].is_null());

    std::thread::sleep(std::time::Duration::from_millis(5));
    std::fs::write(&source_file, "pub fn version() -> u8 { 2 }\n").expect("update source");

    let inspected = request(
        router,
        axum::http::Method::GET,
        &format!("/leases/{lease_id}"),
        serde_json::json!({}),
    )
    .await;

    assert_eq!(
        inspected["bundle_diagnostics"][0]["kind"],
        "possibly_stale_bundle"
    );
    assert_eq!(inspected["bundle_diagnostics"][0]["paths"][0], "src/lib.rs");
}

#[tokio::test]
async fn bundle_rejects_invalid_paths_with_a_bad_request() {
    let temp = make_temp_dir();
    let worker_bin = bin("worker-runtime-host-worker");
    let wrangler_bin = temp.path().join("bin/wrangler");
    make_executable(&wrangler_bin, &fake_wrangler_script());

    let config = test_config(
        &temp,
        &worker_bin.display().to_string(),
        &wrangler_bin.display().to_string(),
        1,
    );
    let router = worker_runtime_host_gen::docs::app(config, test_plan());

    let created = request(
        router.clone(),
        axum::http::Method::POST,
        "/leases",
        serde_json::json!({
            "name": "bad-bundle-test",
            "health_path": "/health",
            "env": "dev",
            "protocol": "http",
            "log_level": "warn"
        }),
    )
    .await;
    let lease_id = created["id"].as_str().expect("id");

    let response = router
        .oneshot(
            Request::builder()
                .method(axum::http::Method::POST)
                .uri(format!("/leases/{lease_id}/bundle"))
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::json!({
                        "runtime_files": [
                            {
                                "path": "/etc/passwd",
                                "content_b64": "bm90IHJlYWxseQ=="
                            }
                        ]
                    })
                    .to_string(),
                ))
                .expect("request"),
        )
        .await
        .expect("response");
    assert_eq!(response.status(), StatusCode::BAD_REQUEST);
}

#[tokio::test]
async fn bundle_accepts_large_prebuilt_payloads() {
    let temp = make_temp_dir();
    let worker_bin = bin("worker-runtime-host-worker");
    let wrangler_bin = temp.path().join("bin/wrangler");
    make_executable(&wrangler_bin, &fake_wrangler_script());

    let config = test_config(
        &temp,
        &worker_bin.display().to_string(),
        &wrangler_bin.display().to_string(),
        1,
    );
    let router = worker_runtime_host_gen::docs::app(config, test_plan());

    let created = request(
        router.clone(),
        axum::http::Method::POST,
        "/leases",
        serde_json::json!({
            "name": "large-bundle-test",
            "health_path": "/health",
            "env": "dev",
            "protocol": "http",
            "log_level": "warn"
        }),
    )
    .await;
    let lease_id = created["id"].as_str().expect("id");
    let large_content = "x".repeat(3 * 1024 * 1024);

    let bundled = request(
        router.clone(),
        axum::http::Method::POST,
        &format!("/leases/{lease_id}/bundle"),
        serde_json::json!({
            "runtime_files": [
                {
                    "path": "large-worker.wasm",
                    "content_b64": base64::Engine::encode(
                        &base64::engine::general_purpose::STANDARD,
                        large_content
                    )
                }
            ],
            "static_files": []
        }),
    )
    .await;

    assert_eq!(bundled["status"]["state"], "bundled");
}
