use serde_json::json;

use super::examples;
use crate::docs_model::ClientContractExample;

pub(super) fn create_lease_example() -> ClientContractExample {
    ClientContractExample {
        title: "Create a lease".to_string(),
        purpose:
            "Allocate an isolated worker runtime that can be bundled and restarted until deleted."
                .to_string(),
        method: "POST".to_string(),
        path: "/leases".to_string(),
        request_example: examples::create_request(),
        response_example: examples::lease_response("created", true),
    }
}

pub(super) fn bundle_runtime_files_example() -> ClientContractExample {
    ClientContractExample {
        title: "Bundle runtime files".to_string(),
        purpose: "Replace the lease runtime and static directories with a complete prebuilt test payload. Lease backends consume prebuilt bundles, so Wrangler build hooks are skipped and callers must rebuild artifacts before uploading after Worker source changes."
            .to_string(),
        method: "POST".to_string(),
        path: "/leases/{id}/bundle".to_string(),
        request_example: json!({
            "runtime_files": [
                { "path": "wrangler.toml", "content_b64": "bmFtZSA9ICJhbHBoYS10ZXN0Ig==" },
                { "path": "worker_entry.mjs", "content_b64": "ZXhwb3J0IGRlZmF1bHQge30K" }
            ],
            "static_files": [
                { "path": "index.html", "content_b64": "PGgxPmFscGhhLXRlc3Q8L2gxPgo=" }
            ],
            "metadata": {
                "source_root": "/home/me/src/food-tracker/food-tracker-serverless",
                "build_command": "worker-build --release",
                "built_at": "2026-04-30T12:34:56Z",
                "artifact_paths": ["build/index.js"],
                "source_paths": ["src/lib.rs", "Cargo.toml"],
                "source_fingerprint": "git:abc123",
                "bundle_description": "food-tracker-serverless/build/index.js generated by worker-build"
            }
        }),
        response_example: examples::lease_response("bundled", true),
    }
}

pub(super) fn restart_lease_example() -> ClientContractExample {
    ClientContractExample {
        title: "Start or restart the lease".to_string(),
        purpose: "Launch the prebuilt worker with the lease backend and wait for readiness on the lease request port while keeping the isolated inspector port reserved for the same lease.".to_string(),
        method: "POST".to_string(),
        path: "/leases/{id}/restart".to_string(),
        request_example: json!({ "persist_state": false, "backend": "miniflare" }),
        response_example: examples::lease_response("starting", false),
    }
}

pub(super) fn inspect_lease_example() -> ClientContractExample {
    ClientContractExample {
        title: "Inspect the lease".to_string(),
        purpose: "Poll until status.state becomes ready.".to_string(),
        method: "GET".to_string(),
        path: "/leases/{id}".to_string(),
        request_example: json!(null),
        response_example: examples::lease_response("ready", false),
    }
}

pub(super) fn delete_lease_example() -> ClientContractExample {
    ClientContractExample {
        title: "Delete the lease".to_string(),
        purpose: "Stop the worker and clean up the lease directories.".to_string(),
        method: "DELETE".to_string(),
        path: "/leases/{id}".to_string(),
        request_example: json!(null),
        response_example: examples::lease_response("stopped", false),
    }
}
